theme: jekyll-theme-cayman

title: Welcome to Sayed Jobaer's Homepage!
description: >
  Ph.D. in Information and Communication Intelligent Systems<br>
  Donghua University (211, Double First-Class), Shanghai, China<br><br>
  <a href="mailto:sayedjobaer@hotmail.com">Email</a> ·
  <a href="https://github.com/Sayed-Jobaer" target="_blank">GitHub</a> ·
  <a href="/assets/cv.pdf" target="_blank">CV</a> ·
  <a href="https://scholar.google.com/citations?user=fCM8lL8AAAAJ&hl=en" target="_blank">
    Google Scholar
  </a>



