theme: jekyll-theme-cayman

title: Welcome to Foysal Ahmed's Homepage!

description: >
  Ph.D. Student in Information and Communication Intelligent Systems<br>
  Donghua University (211, Double First-Class), Shanghai, China <br><br>
  <a href="foysal.9@outlook.com">Email</a> ·
  <a href="https://github.com/foysalahmed10" target="_blank">GitHub</a> ·
  <a href="/assets/cv.pdf" target="_blank">CV</a> ·
  <a href="https://scholar.google.com/citations?user=1HUchzEAAAAJ&hl=en" target="_blank">
    Google Scholar </a>


