theme: jekyll-theme-cayman

title: Welcome to Foysal Ahmed's Homepage!

description: >
  Ph.D. Student in Information and Communication Intelligent Systems<br>
  Donghua University (211, Double First-Class), Shanghai, China 


